# Generated by Django 4.2.11 on 2024-03-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_tenants'),
        ('users', '0002_customuser_assigned_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='properties.property'),
        ),
    ]
