# Generated by Django 4.2.11 on 2025-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="",
                help_text="Leave blank to use the default avatar.",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
