# Generated by Django 4.2.11 on 2024-03-29 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'income'), (2, 'expense')])),
                ('amount', models.FloatField()),
                ('note', models.CharField(max_length=180)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Paid'), (2, 'Void')], default=0)),
                ('overdue_fee', models.FloatField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
