# Generated by Django 4.2.11 on 2024-03-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_month',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
