# Generated by Django 4.2.11 on 2024-04-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('finance', '0003_transaction_due_date_transaction_transaction_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_charge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.charge'),
        ),
    ]
