# Generated by Django 4.2.11 on 2024-04-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('finance', '0004_transaction_stripe_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_charge',
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.invoice'),
        ),
    ]
