# Generated by Django 4.2.11 on 2024-03-27 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lease_end', models.DateField()),
                ('rent_amount', models.FloatField()),
                ('next_rent_due', models.DateField()),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
