# Generated by Django 4.2.11 on 2024-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='outstanding_rent',
            field=models.FloatField(default=0),
        ),
    ]
