# Generated by Django 4.2.11 on 2024-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_rename_renter_tenant_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='apartment',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
