# Generated by Django 4.2.11 on 2024-03-27 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenant_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident', to=settings.AUTH_USER_MODEL),
        ),
    ]
