# Generated by Django 4.2.11 on 2024-03-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenant_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='overdue_fee',
            field=models.FloatField(default=0),
        ),
    ]
