# Generated by Django 4.2.11 on 2024-03-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_overdue_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='current_rent_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_rent_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
