# Generated by Django 4.2.11 on 2024-04-05 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0009_tenant_current_rent_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='overdue_fee_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL),
        ),
    ]
