# Generated by Django 4.2.11 on 2024-03-26 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
