# Generated by Django 4.2.11 on 2024-03-26 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_alter_property_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='rented_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
