# Generated by Django 4.2.11 on 2024-03-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_tenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tenants',
        ),
    ]
