# Generated by Django 4.2.11 on 2024-03-26 22:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_code', to='properties.property')),
            ],
        ),
    ]
