# Generated by Django 4.2.11 on 2024-03-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('properties', '0005_invitationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyTenant',
            fields=[
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenants.tenant',),
        ),
    ]
