# Generated by Django 4.2.11 on 2024-03-27 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_proxytenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='apartment',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='lease_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='next_rent_due',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='rent_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='properties.property'),
        ),
    ]
