# Generated by Django 4.2.11 on 2024-03-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_invitationcode_apartment_invitationcode_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcode',
            name='code',
        ),
    ]
