# Generated by Django 4.2.11 on 2024-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_invitationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
