# Generated by Django 4.2.11 on 2024-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_invitationcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
