# Generated by Django 4.2.11 on 2024-03-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_invitationcode_code_alter_invitationcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='name',
            field=models.TextField(default='Placeholder', max_length=50),
        ),
    ]
