# Generated by Django 4.2.11 on 2024-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_invitationcode_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='tenant_name',
            field=models.CharField(default='Jane Doe', max_length=70, verbose_name='Tenant namesss:'),
        ),
    ]
