# Generated by Django 4.2.11 on 2024-04-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_invitationcode_tenant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='tenant_name',
            field=models.CharField(default='Jane Doe', max_length=70),
        ),
        migrations.CreateModel(
            name='PropertyNotice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('posted_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('posted_by', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_notice', to='properties.property')),
            ],
        ),
    ]
