# Generated by Django 4.2.11 on 2024-04-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_invitationcode_tenant_name_propertynotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertynotice',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
