# Generated by Django 4.2.11 on 2024-04-01 22:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_propertynotice_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
