# Generated by Django 4.2.11 on 2024-04-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_property_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
