# Generated by Django 4.2.11 on 2024-04-06 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0019_alter_invitationcode_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contractors',
            field=models.ManyToManyField(blank=True, related_name='contractors', to=settings.AUTH_USER_MODEL),
        ),
    ]
