# Generated by Django 4.2.11 on 2024-04-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_contractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='contractor_code',
            field=models.BooleanField(default=False),
        ),
    ]
