# Generated by Django 4.2.11 on 2024-04-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_invitationcode_contractor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='invited_contractors', to='properties.property'),
        ),
    ]
