# Generated by Django 4.2.11 on 2024-04-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_rename_properties_invitationcode_contractor_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcode',
            name='contractor_code',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='contractor_properties',
        ),
    ]
