# Generated by Django 4.2.11 on 2024-04-06 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0024_remove_invitationcode_contractor_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contractors',
        ),
        migrations.AddField(
            model_name='property',
            name='assigned_contractor',
            field=models.ManyToManyField(blank=True, related_name='assigned_contractor', to=settings.AUTH_USER_MODEL),
        ),
    ]
