# Generated by Django 4.2.11 on 2024-04-07 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0025_remove_property_contractors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='assigned_contractor',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_contractor', to=settings.AUTH_USER_MODEL),
        ),
    ]
