# Generated by Django 4.2.11 on 2024-03-28 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0013_alter_invitationcode_tenant_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(max_length=280)),
                ('urgent', models.BooleanField(default=False)),
                ('contractor_note', models.TextField(max_length=280)),
                ('scheduled_date', models.DateTimeField(blank=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(default='anon', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='contractor', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_request', to='properties.property')),
                ('submitted_by', models.ForeignKey(default='anon', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='submitted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
