# Generated by Django 4.2.11 on 2024-03-28 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='contractor',
            field=models.ForeignKey(default='anon', limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='contractor', to=settings.AUTH_USER_MODEL),
        ),
    ]
