# Generated by Django 4.2.11 on 2024-03-28 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0004_alter_maintenancerequest_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='contractor',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='scheduled_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
