# Generated by Django 4.2.11 on 2024-03-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenancerequest_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'In-progress'), (2, 'Completed'), (3, 'Cancelled')], default=0),
        ),
    ]
