# Generated by Django 4.2.11 on 2024-03-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenancerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='location',
            field=models.CharField(default='Unknown', max_length=120),
        ),
    ]
