# Generated by Django 4.2.11 on 2024-03-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenancerequest_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='scheduled_date',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
