# Generated by Django 4.2.11 on 2024-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_maintenancerequest_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
