# Generated by Django 4.2.11 on 2024-04-07 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_worker_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
